language: ruby
cache: bundler
branches:
  only:
  - dev
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination _site
deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
after_deploy:
  - cp CNAME ./_site/CNAME
