baseurl: ""
url: "https://www.saikiransripada.com/"
title: "Sai Kiran Sripada"

# This is used by feed.xml. Uncomment if you want to use it.
description: "A full-stack developer based in India, currently focusing on Python, Node.js, React, Vue.js and Ruby Technologies."

date_format: "%b %-d, %Y"

markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jemoji
exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
