# General settings
title: Sai Kiran Sripada
title_html: "<b>Sai Kiran</b> Sripada"
pitch:
description: A full-stack developer, currently focusing on Python, Node.js, React, Vue.js and Ruby Technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.saikiransripada.com" # the base hostname & protocol for your site, e.g. http://example.com

nb_posts_page: 3
dateformat: "%b %-d, %Y"

cta:
  like: "Do you enjoy the blog?"
  post: "Did you like that post?"
  rss: ["You can suscribe to the", "RSS feed", ""]
  twitter: ["or follow", "on Twitter"]

archive: "Welcome to the archives of this blog. Below, you will find all published posts listed in reverse chronological order."
notfound: "I guess this page has moved somewhere else..."

# Author
author: Sai Kiran Sripada
email: hello@saikiransripada.com
twitter_username: wp_user
github_username: saikiransripada
keybase_username: saikiransripada
linkedin_username: saikiransripada
author_website: https://www.saikiransripada.com/

paginate: 3
paginate_path: /page/:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes"]
permalink: pretty
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-assets
  - jekyll-last-modified-at
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
