baseurl: ""
url: "http://localhost:4000"
title: "Sai Kiran Sripada"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

date_format: "%b %-d, %Y"

markdown: kramdown
sass:
  style: compressed
gems:
  - jemoji
exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
