# The main config file for your Jekyll template

# Site settings
title: Sai Kiran Sripada
desc: >
  This blog is a timeline of my life. A blog to document my ideas, research and personal feelings for future reference.

url: https://www.kiran.im
baseurl: ''
permalink: /:title/

# Meta settings
email: mail@kiran.im
author: Sai Kiran Sripada
twitter_username: wp_user
github_username: serialization

# Optional settings
google_analytics: 'UA-67531538-2'
comments: true

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Navigation settings
navigation:
  - title: Blog
    url: /blog/
    desc: Some weird ramblings I occasionally publish and instantly forget
  - title: Projects
    url: /projects/
    desc: Projects that I have built in my spare time and that I am proud to showcase
  - title: About
    url: /about/
    desc: Learn about me, my hobbies and some other cool things
  - title: Contact
    url: /contact/
    desc: Contact

# Front Matter settings
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Compress CSS
sass:
  style: compressed

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Build settings
include:
  - _pages
exclude:
  - README.md
  - vendor
plugins:
  - jekyll-paginate
