# Site settings
title:       Sai Kiran Sripada
author:      Sai Kiran Sripada
description: "This blog is a timeline of my life. A blog to document my ideas, research and personal feelings for future reference."
baseurl:     ""
url:         "https://www.saikiransripada.com"
date_format: "%b %-d, %Y"
header_pages:
 - projects.md
 - about.md

google_analytics:

# Optional features
show_related_posts:   false
enable_mathjax: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:title/
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
