version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
    working_directory: ~/www
    steps:
      - checkout
      #- run: rvm use default
      #- run: gem update --system
      - run: gem install bundler --version=1.17.3
      - run: bundle install
      - run: JEKYLL_ENV=production bundle exec jekyll build --destination _site
      - run: cp CNAME ./_site/CNAME
      - run: echo "Build finished!"
      - persist_to_workspace:
            root: _site
            paths:
              - ""

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # Build on any branch except github pages
      - build:
          filters:
            branches:
              ignore: gh-pages
      # Deploy only on master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - dev