version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:2.7
        environment:
          BUNDLE_VERSION: 1.17.3
    working_directory: ~/repo

jobs:
  build:
    executor: ruby-executor
    steps:
      - checkout
      - restore_cache:
          key: bundler-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Bundler 1.17.3
          command: gem install bundler -v 1.17.3
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bundler-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build Jekyll Site
          command: JEKYLL_ENV=production bundle exec jekyll build --destination _site
      - run:
          name: Copy CNAME
          command: cp CNAME ./_site/CNAME
      - persist_to_workspace:
          root: ~/repo
          paths:
            - _site

  deploy:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure Git
          command: |
            git config --global user.email "deploy@circleci.org"
            git config --global user.name "Deployment Bot"
            # git checkout -b master
            # git status
            # git add .
            # git commit -m "Deploy to GitHub Pages"
      - run:
          name: Push to GitHub
          command: |
            git remote add origin_ssh "git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git"
            git push origin_ssh master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
