defaults: &defaults
  working_directory: ~/www
version: 2.1

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler -v 2.3.26
      - run:
          name: "Build site"
          command: JEKYLL_ENV=production bundle exec jekyll build --destination _site
      - persist_to_workspace:
          root: _site
          paths:
            - ""
  deploy:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - attach_workspace:
          at: ~/www/_site

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev